### ISSUE TITLE
Loot Sheet Would Not Open After Dropping Container Into It

### ISSUE THREAD

**Issue by maxipad1991junkmail** [SvenWerlen/fvtt-loot-sheet-npc-pf1#12] opened 2021-02-08 03:57 UTC
I was not able to drop a container from another sheet into the loot sheet.  To get around this, I changed the type of sheet to the standard PF1E loot sheet, then changed it back.  However, after changing it back, the character sheet would no longer open at all.

The fix was to disable this module to make it switch to another type of loot sheet, but Noon said it seemed that the module doesn't yet have support for containers.

**Comment by SvenWerlen** [comment] 2021-02-12 03:16
Duplicate of #7 
Btw, I implemented limited support for container in `1.9.0` (soon released)

**Closed as completed by SvenWerlen** 2021-02-12 03:16 UTC
Labels: duplicate
